### PR TITLE
more user friendly interfaces

### PR DESCRIPTION
**Pull request by Charliechen1**
Hi dude,

During my one fraud modelling competition I found your code quite useful in finding patterns in user action sequences. It efficient and precise. However, I found it a little bit complicated to import your code into my projects. Therefore, I made some tiny modifications and hope it can help your project to be more friendly to one who want to utilize your wonderful contribution. 

Best,
Charlie Chen 陈家礼

### CODE REVIEW

**Comment by chuanconggao** [comment]
I have been interested in wrapping this into a public library, with importable API, possibly available on PyPi.

The major issue of this pull request is that it completely removes the terminal usage. Arguably, most users (including me) use it as part of the command line workflow.

**Comment by Charliechen1** [comment]
Well, thx, then how about alternatively adding a simple interface? Or its sad for API user...

**Comment by chuanconggao** [comment]
Sure. I will add it. Since I need to put it on PyPi, it may take a few days.

**Comment by Charliechen1** [comment]
Thx~

**Comment by chuanconggao** [comment]
Hi, I have added the API. Feel free to leave some feedback.

I will further put it on PyPi.

**Pull request closed without merging**
